######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 5 16:49:29 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QMAKE_CXXFLAGS += -std=c++11

# Input
HEADERS += transfer_window.h
SOURCES += main.cpp transfer_window.cpp
