######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 5 16:49:29 2016
######################################################################

TEMPLATE = app
TARGET = QTransfer
DEPENDPATH += .
INCLUDEPATH += .

QT += network core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

QMAKE_CXXFLAGS += -std=c++11
QMAKE_CFLAGS_ISYSTEM = -I

# Input
HEADERS += transfer_window.h
SOURCES += main.cpp transfer_window.cpp
